/**
 * KELIME LAB 1.1 - LISTA OFICIAL COMPLETA
 */

const allWords = [
    {word:"aç",correct:"hambriento/a"},{word:"açık",correct:"abierto / claro (color)"},{word:"açmak",correct:"abrir"},
    {word:"ad (isim)",correct:"nombre"},{word:"adres",correct:"dirección"},{word:"Affedersiniz",correct:"Perdone"},
    {word:"Afiyet olsun",correct:"Buen provecho"},{word:"ağaç",correct:"árbol"},{word:"Ağustos",correct:"agosto"},
    {word:"Akrep Burcu",correct:"Escorpio"},{word:"akşam",correct:"tarde / noche"},{word:"alışveriş",correct:"compras"},
    {word:"alkol",correct:"alcohol"},{word:"Almanya",correct:"Alemania"},{word:"alt",correct:"debajo"},
    {word:"anahtar",correct:"llave"},{word:"anlamak",correct:"entender"},{word:"anneler günü",correct:"día de la madre"},
    {word:"araba",correct:"coche"},{word:"Aralık",correct:"diciembre"},{word:"aramak",correct:"buscar / llamar"},
    {word:"arkadaş",correct:"amigo/a"},{word:"artı",correct:"más (suma)"},{word:"Aslan Burcu",correct:"Leo"},
    {word:"avukat",correct:"abogado/a"},{word:"Avusturya",correct:"Austria"},{word:"ay",correct:"mes / luna"},
    {word:"aynı",correct:"mismo"},{word:"az",correct:"poco"},{word:"baba",correct:"padre"},
    {word:"bahçe",correct:"jardín"},{word:"bakmak",correct:"mirar"},{word:"bale",correct:"ballet"},
    {word:"balık",correct:"pescado"},{word:"Balık Burcu",correct:"Piscis"},{word:"banka",correct:"banco"},
    {word:"banyo yapmak",correct:"bañarse"},{word:"bardak",correct:"vaso"},{word:"Başak Burcu",correct:"Virgo"},
    {word:"başarılı",correct:"exitoso/a"},{word:"başlamak",correct:"empezar"},{word:"bavul",correct:"maleta"},
    {word:"bay",correct:"señor"},{word:"bayan",correct:"dama"},{word:"bayılmak",correct:"desmayarse / encantar"},
    {word:"bayram",correct:"fiesta / festivo"},{word:"bebek",correct:"bebé"},{word:"bekâr",correct:"soltero/a"},
    {word:"beraber",correct:"juntos/as"},{word:"beslenmek",correct:"alimentarse"},{word:"bey",correct:"señor"},
    {word:"beyaz",correct:"blanco"},{word:"bilet",correct:"billete / ticket"},{word:"biletçi",correct:"taquillero/a"},
    {word:"bilgisayar",correct:"ordenador"},{word:"bilgisayar oyunu",correct:"videojuego"},{word:"bilmek",correct:"saber"},
    {word:"bina",correct:"edificio"},{word:"binmek",correct:"subir / montar"},{word:"birçok",correct:"muchos/as"},
    {word:"biriktirmek",correct:"ahorrar / acumular"},{word:"bitmek",correct:"terminar"},{word:"Boğa Burcu",correct:"Tauro"},
    {word:"bol bol",correct:"en abundancia / muchísimo"},{word:"Bol şanslar",correct:"Buena suerte"},
    {word:"bölü",correct:"dividido por, entre"},{word:"borç",correct:"deuda"},{word:"boş",correct:"vacío/a, libre"},
    {word:"boş zaman",correct:"tiempo libre"},{word:"büfe",correct:"quiosco"},{word:"bugün",correct:"hoy"},
    {word:"bulaşık",correct:"vajilla"},{word:"buluşmak",correct:"encontrarse"},{word:"burada",correct:"aquí"},
    {word:"burçlar",correct:"signos del zodíaco"},{word:"büro",correct:"oficina"},{word:"bütün",correct:"todo/a"},
    {word:"büyük",correct:"grande"},{word:"çalışkan",correct:"trabajador/a"},{word:"çalışmak",correct:"trabajar / estudiar"},
    {word:"çamaşır",correct:"colada / ropa"},{word:"cami",correct:"mezquita"},{word:"çanta",correct:"bolso"},
    {word:"çarpı",correct:"por (multiplicar)"},{word:"Çarşamba",correct:"miércoles"},{word:"çarşı",correct:"mercado"},
    {word:"çay",correct:"té"},{word:"çenesiz",correct:"muy hablador/a"},{word:"cesur",correct:"valiente"},
    {word:"cetvel",correct:"regla"},{word:"cevap",correct:"respuesta"},{word:"ceviz",correct:"nuez"},
    {word:"çiçek",correct:"flor"},{word:"ciddi",correct:"serio/a"},{word:"çıkmak",correct:"salir"},
    {word:"Çin",correct:"China"},{word:"çirkin",correct:"feo/a"},{word:"çocuk",correct:"niño/a"},
    {word:"çok",correct:"muy, mucho/a, muchos/as"},{word:"Çok yaşa",correct:"Salud (estornudo)"},
    {word:"çöp kutusu",correct:"papelera"},{word:"Cuma",correct:"viernes"},{word:"Cumartesi",correct:"sábado"},
    {word:"çünkü",correct:"porque"},{word:"dağınık",correct:"desordenado/a"},{word:"dalgalı saçlı",correct:"pelo ondulado"},
    {word:"dans",correct:"danza"},{word:"dar",correct:"estrecho/a"},{word:"defter",correct:"cuaderno"},
    {word:"değişik",correct:"diferente"},{word:"demek",correct:"decir"},{word:"deniz",correct:"mar"},
    {word:"dergi",correct:"revista"},{word:"ders",correct:"clase / lección"},{word:"dikkatli",correct:"cuidadoso/a"},
    {word:"dikkatsiz",correct:"descuidado/a"},{word:"dinlemek",correct:"escuchar"},{word:"dinlenmek",correct:"descansar"},
    {word:"dışarı",correct:"afuera"},{word:"dizi",correct:"serie"},{word:"doğum günü",correct:"cumpleaños"},
    {word:"doğum tarihi",correct:"fecha nacimiento"},{word:"dolap",correct:"armario"},{word:"dolaşmak",correct:"pasear"},
    {word:"dolu",correct:"lleno/a"},{word:"domates",correct:"tomate"},{word:"dönmek",correct:"volver"},
    {word:"dosya",correct:"archivo"},{word:"düğün",correct:"boda"},{word:"durak",correct:"parada"},
    {word:"durmak",correct:"parar"},{word:"duş almak",correct:"ducharse"},{word:"duvar",correct:"pared"},
    {word:"düz saçlı",correct:"pelo liso"},{word:"düzenli",correct:"ordenado/a"},{word:"eczacı",correct:"farmacéutico/a"},
    {word:"eczane",correct:"farmacia"},{word:"eğlenceli",correct:"divertido/a"},{word:"Ekim",correct:"octubre"},
    {word:"ekmek",correct:"pan"},{word:"ekonomi",correct:"economía"},{word:"eksi",correct:"menos"},{word:"derece",correct:"grado"},
    {word:"elbise",correct:"vestido / ropa"},{word:"elma",correct:"manzana"},{word:"emekli",correct:"jubilado/a"},
    {word:"erkek",correct:"hombre"},{word:"erken",correct:"temprano"},{word:"eş",correct:"esposo/a, cónyuge"},
    {word:"eski",correct:"antiguo/a"},{word:"esmer",correct:"moreno/a"},{word:"etmek",correct:"hacer (auxiliar)"},
    {word:"ev",correct:"casa"},{word:"evli",correct:"casado/a"},{word:"Eylül",correct:"septiembre"},
    {word:"fabrika",correct:"fábrica"},{word:"fakir",correct:"pobre"},{word:"fare",correct:"ratón"},
    {word:"farklı",correct:"diferente"},{word:"fikir",correct:"idea"},{word:"film",correct:"película"},
    {word:"fındık",correct:"avellana"},{word:"fırça",correct:"cepillo"},{word:"fırın",correct:"horno"},
    {word:"fotoğraf çekmek",correct:"hacer fotos"},{word:"Fransa",correct:"Francia"},{word:"futbol",correct:"fútbol"},
    {word:"futbolcu",correct:"futbolista"},{word:"garson",correct:"camarero/a"},{word:"gazete",correct:"periódico"},
    {word:"geç",correct:"tarde"},{word:"geçmek",correct:"pasar"},{word:"Geçmiş olsun",correct:"Que te mejores"},
    {word:"gelmek",correct:"venir"},{word:"genç",correct:"joven"},{word:"genellikle",correct:"generalmente"},
    {word:"geniş",correct:"ancho/a"},{word:"gezi",correct:"excursión"},{word:"gezmek",correct:"pasear / viajar"},
    {word:"girmek",correct:"entrar"},{word:"gitar",correct:"guitarra"},{word:"gitmek",correct:"ir"},
    {word:"gökkuşağı",correct:"arcoíris"},{word:"görüşmek",correct:"verse / reunirse"},{word:"Görüşürüz",correct:"Nos vemos"},
    {word:"gösteri",correct:"espectáculo"},{word:"göz",correct:"ojo"},{word:"gri",correct:"gris"},
    {word:"güçlü",correct:"fuerte"},{word:"güçsüz",correct:"débil"},{word:"gül",correct:"rosa (flor)"},
    {word:"Güle güle",correct:"Adiós (quien se queda)"},{word:"gün",correct:"día"},{word:"Günaydın",correct:"Buenos días"},
    {word:"gündüz",correct:"de día"},{word:"güzel",correct:"bonito/a, guapa"},{word:"hafta içi",correct:"entre semana"},
    {word:"hafta sonu",correct:"fin de semana"},{word:"hâl",correct:"estado / salud"},{word:"halı",correct:"alfombra"},
    {word:"hanım",correct:"señora"},{word:"hasta",correct:"enfermo/a"},{word:"hastalık",correct:"enfermedad"},
    {word:"hastane",correct:"hospital"},{word:"hava",correct:"aire / tiempo"},{word:"havuç",correct:"zanahoria"},
    {word:"hayal",correct:"sueño / ilusión"},{word:"hayat",correct:"vida"},{word:"hazır",correct:"listo/a, preparado/a"},
    {word:"Haziran",correct:"junio"},{word:"hazırlamak",correct:"preparar"},{word:"hazırlanmak",correct:"prepararse"},
    {word:"hediye",correct:"regalo"},{word:"hemşire",correct:"enfermero/a"},{word:"her",correct:"cada"},
    {word:"her zaman",correct:"siempre"},{word:"heyecanlı",correct:"emocionado/a"},{word:"hiç",correct:"nada / nunca"},
    {word:"hiçbir zaman",correct:"nunca"},{word:"hızlı",correct:"rápido/a"},{word:"Hoş bulduk",correct:"Respuesta a bienvenida"},
    {word:"Hoş geldin",correct:"Bienvenido/a"},{word:"Hoşça kal",correct:"Adiós (quien se va)"},{word:"hoşlanmak",correct:"gustar"},
    {word:"hukuk",correct:"derecho"},{word:"içecek",correct:"bebida"},{word:"içeri",correct:"adentro"},
    {word:"ideal",correct:"ideal"},{word:"İkizler Burcu",correct:"Géminis"},{word:"ilkbahar",correct:"primavera"},
    {word:"inek",correct:"vaca"},{word:"İngitlere",correct:"Inglaterra"},{word:"inşallah",correct:"ojalá"},
    {word:"insan",correct:"persona"},{word:"internete girmek",correct:"entrar en internet"},{word:"iş",correct:"trabajo"},
    {word:"iş yeri",correct:"lugar de trabajo"},{word:"işadamı",correct:"hombre de negocios"},{word:"ıspanak",correct:"espinaca"},
    {word:"İspanya",correct:"España"},{word:"istasyon",correct:"estación"},{word:"İtalya",correct:"Italia"},
    {word:"iyi",correct:"bien, bueno/a"},{word:"ızgara",correct:"parrilla"},{word:"izlemek",correct:"ver / mirar"},
    {word:"Japonya",correct:"Japón"},{word:"jeton",correct:"ficha"},{word:"jilet",correct:"cuchilla"},
    {word:"kaç",correct:"cuánto/a, cuántos/as"},{word:"kaçıncı",correct:"qué número"},{word:"kadın",correct:"mujer"},
    {word:"kafe",correct:"cafetería"},{word:"kahvaltı etmek",correct:"desayunar"},{word:"kahve",correct:"café"},
    {word:"kahverengi",correct:"marrón"},{word:"kahverengi saçlı",correct:"marrón (pelo)"},{word:"kalabalık",correct:"concurrido/a"},
    {word:"kalem",correct:"lápiz / bolígrafo"},{word:"kalkmak",correct:"levantarse"},{word:"kalmak",correct:"quedarse"},
    {word:"kalp",correct:"corazón"},{word:"kampus",correct:"campus"},{word:"kanepe",correct:"sofá"},
    {word:"kantin",correct:"cantina"},{word:"kapalı",correct:"cerrado/a"},{word:"kapatmak",correct:"cerrar"},
    {word:"kapı",correct:"puerta"},{word:"kasap",correct:"carnicero/a, carnicería"},{word:"Kasım",correct:"noviembre"},
    {word:"kasiyer",correct:"cajero/a"},{word:"kat",correct:"piso, planta"},{word:"kebap",correct:"kebab"},
    {word:"kedi",correct:"gato"},{word:"kel",correct:"calvo/a"},{word:"kestane",correct:"castaño/a"},
    {word:"kibar",correct:"amable"},{word:"kilo",correct:"kilo"},{word:"kira",correct:"alquiler"},
    {word:"kırmızı",correct:"rojo"},{word:"kış",correct:"invierno"},{word:"kısa saçlı",correct:"pelo corto"},
    {word:"kişi",correct:"persona"},{word:"kıskanç",correct:"celoso/a"},{word:"kitap",correct:"libro"},
    {word:"kitaplık",correct:"estantería"},{word:"kıvırcık saçlı",correct:"pelo rizado"},{word:"kız",correct:"chica / hija"},
    {word:"kızgın",correct:"enfadado/a"},{word:"kızıl saçlı",correct:"pelirrojo/a"},{word:"Koç Burcu",correct:"Aries"},
    {word:"kolay",correct:"fácil"},{word:"koltuk",correct:"sillón"},{word:"komik",
